name: Sync and Create PR

on:
  push:
    branches:
      - main  # or master, adjust if needed

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create sync branch
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git checkout -b sync-branch-${{ github.sha }}

      - name: Push to target repo
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git remote add target https://$SYNC_TOKEN@github.com/a0a7/publicbroadcastarr.git
          git push target sync-branch-${{ github.sha }}:sync-branch-${{ github.sha }}

      - name: Create Pull Request
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          commit-message: Sync from svtplayarr
          title: 'Sync update from svtplayarr'
          body: 'Automated PR to sync changes from svtplayarr.'
          base: main
          head: sync-branch-${{ github.sha }}
          repository: a0a7/publicbroadcastarr
