name: Sync to publicbroadcastarr as PR

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout svtplayarr repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Set up Git user
        run: |
          git config user.name "a0a7"
          git config user.email "<your-email>@users.noreply.github.com"

      - name: Fetch publicbroadcastarr default branch
        run: |
          git remote add target https://a0a7:${{ secrets.SYNC_TOKEN }}@github.com/a0a7/publicbroadcastarr.git
          git fetch target main

      - name: Check for differences
        id: diff
        run: |
          git log target/main..HEAD --oneline
          if [ "$(git rev-list --count target/main..HEAD)" -eq 0 ]; then
            echo "no_diff=true" >> $GITHUB_OUTPUT
          else
            echo "no_diff=false" >> $GITHUB_OUTPUT
          fi

      - name: Push branch to publicbroadcastarr
        if: steps.diff.outputs.no_diff == 'false'
        run: |
          export BRANCH=sync-from-svtplayarr-$(date +%Y%m%d-%H%M%S)
          git checkout -b $BRANCH
          git push target $BRANCH
          echo "branch=$BRANCH" >> $GITHUB_ENV

      - name: Create PR in publicbroadcastarr
        if: steps.diff.outputs.no_diff == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.SYNC_TOKEN }}
          script: |
            const branch = process.env.BRANCH;
            const { data: pr } = await github.pulls.create({
              owner: 'a0a7',
              repo: 'publicbroadcastarr',
              head: branch,
              base: 'main',
              title: `Sync from svtplayarr (${branch})`,
              body: 'Automated PR to sync commits from svtplayarr.'
            });
            console.log('PR created:', pr.html_url);
